WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
GRID_WIDTH = int(WINDOW_WIDTH)
GRID_HEIGHT = int(WINDOW_HEIGHT)
CELL_SIZE = 20

# Размеры сетки в ячейках
WIDTH_CELL_COUNT = int(GRID_WIDTH / CELL_SIZE)
HEIGHT_CELL_COUNT = int(GRID_HEIGHT / CELL_SIZE)

# Цвета
BG_COLOR = (0, 0, 0)
GRID_COLOR = (40, 40, 40)
APPLE_COLOR = (255, 0, 0)
APPLE_OUTER_COLOR = (155, 0, 0)
SNAKE_COLOR = (0, 255, 0)
SNAKE_OUTER_COLOR = (0, 155, 0)

UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"

FPS = 30

SPEED = 10
